/* state-t-flipflop.c generated by valac 0.24.0, the Vala compiler
 * generated from state-t-flipflop.vala, do not modify */

/* 
 * SmartSim - Digital Logic Circuit Designer and Simulator
 *   
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *   
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *   
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *   
 *   Filename: componentstate/state-t-flipflop.vala
 *   
 *   Copyright Ashley Newson 2013
 */

#include <glib.h>
#include <glib-object.h>
#include <cairo.h>


#define TYPE_COMPONENT_STATE (component_state_get_type ())
#define COMPONENT_STATE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COMPONENT_STATE, ComponentState))
#define COMPONENT_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_COMPONENT_STATE, ComponentStateClass))
#define IS_COMPONENT_STATE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COMPONENT_STATE))
#define IS_COMPONENT_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_COMPONENT_STATE))
#define COMPONENT_STATE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_COMPONENT_STATE, ComponentStateClass))

typedef struct _ComponentState ComponentState;
typedef struct _ComponentStateClass ComponentStateClass;
typedef struct _ComponentStatePrivate ComponentStatePrivate;

#define TYPE_COMPILED_CIRCUIT (compiled_circuit_get_type ())
#define COMPILED_CIRCUIT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COMPILED_CIRCUIT, CompiledCircuit))
#define COMPILED_CIRCUIT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_COMPILED_CIRCUIT, CompiledCircuitClass))
#define IS_COMPILED_CIRCUIT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COMPILED_CIRCUIT))
#define IS_COMPILED_CIRCUIT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_COMPILED_CIRCUIT))
#define COMPILED_CIRCUIT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_COMPILED_CIRCUIT, CompiledCircuitClass))

typedef struct _CompiledCircuit CompiledCircuit;
typedef struct _CompiledCircuitClass CompiledCircuitClass;

#define TYPE_COMPONENT_INST (component_inst_get_type ())
#define COMPONENT_INST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COMPONENT_INST, ComponentInst))
#define COMPONENT_INST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_COMPONENT_INST, ComponentInstClass))
#define IS_COMPONENT_INST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COMPONENT_INST))
#define IS_COMPONENT_INST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_COMPONENT_INST))
#define COMPONENT_INST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_COMPONENT_INST, ComponentInstClass))

typedef struct _ComponentInst ComponentInst;
typedef struct _ComponentInstClass ComponentInstClass;

#define TYPE_TFLIPFLOP_COMPONENT_STATE (tflipflop_component_state_get_type ())
#define TFLIPFLOP_COMPONENT_STATE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TFLIPFLOP_COMPONENT_STATE, TFlipflopComponentState))
#define TFLIPFLOP_COMPONENT_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TFLIPFLOP_COMPONENT_STATE, TFlipflopComponentStateClass))
#define IS_TFLIPFLOP_COMPONENT_STATE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TFLIPFLOP_COMPONENT_STATE))
#define IS_TFLIPFLOP_COMPONENT_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TFLIPFLOP_COMPONENT_STATE))
#define TFLIPFLOP_COMPONENT_STATE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TFLIPFLOP_COMPONENT_STATE, TFlipflopComponentStateClass))

typedef struct _TFlipflopComponentState TFlipflopComponentState;
typedef struct _TFlipflopComponentStateClass TFlipflopComponentStateClass;
typedef struct _TFlipflopComponentStatePrivate TFlipflopComponentStatePrivate;

#define TYPE_CONNECTION (connection_get_type ())
#define CONNECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CONNECTION, Connection))
#define CONNECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CONNECTION, ConnectionClass))
#define IS_CONNECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CONNECTION))
#define IS_CONNECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CONNECTION))
#define CONNECTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CONNECTION, ConnectionClass))

typedef struct _Connection Connection;
typedef struct _ConnectionClass ConnectionClass;
#define _connection_unref0(var) ((var == NULL) ? NULL : (var = (connection_unref (var), NULL)))
#define _component_inst_unref0(var) ((var == NULL) ? NULL : (var = (component_inst_unref (var), NULL)))

struct _ComponentState {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ComponentStatePrivate * priv;
	CompiledCircuit* compiledCircuit;
	ComponentInst** ancestry;
	gint ancestry_length1;
	ComponentInst* componentInst;
	gint renderQueueID;
	gint processQueueID;
	gboolean display;
};

struct _ComponentStateClass {
	GTypeClass parent_class;
	void (*finalize) (ComponentState *self);
	void (*update) (ComponentState* self);
	void (*click) (ComponentState* self);
	void (*render) (ComponentState* self, cairo_t* context);
	gboolean (*get_alwaysUpdate) (ComponentState* self);
};

struct _TFlipflopComponentState {
	ComponentState parent_instance;
	TFlipflopComponentStatePrivate * priv;
};

struct _TFlipflopComponentStateClass {
	ComponentStateClass parent_class;
};

struct _TFlipflopComponentStatePrivate {
	Connection* toggleWire;
	Connection* clockWire;
	Connection* outputWire;
	Connection* outputNotWire;
	gboolean output;
	gboolean previousClockSignal;
};


static gpointer tflipflop_component_state_parent_class = NULL;

gpointer component_state_ref (gpointer instance);
void component_state_unref (gpointer instance);
GParamSpec* param_spec_component_state (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_component_state (GValue* value, gpointer v_object);
void value_take_component_state (GValue* value, gpointer v_object);
gpointer value_get_component_state (const GValue* value);
GType component_state_get_type (void) G_GNUC_CONST;
gpointer compiled_circuit_ref (gpointer instance);
void compiled_circuit_unref (gpointer instance);
GParamSpec* param_spec_compiled_circuit (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_compiled_circuit (GValue* value, gpointer v_object);
void value_take_compiled_circuit (GValue* value, gpointer v_object);
gpointer value_get_compiled_circuit (const GValue* value);
GType compiled_circuit_get_type (void) G_GNUC_CONST;
gpointer component_inst_ref (gpointer instance);
void component_inst_unref (gpointer instance);
GParamSpec* param_spec_component_inst (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_component_inst (GValue* value, gpointer v_object);
void value_take_component_inst (GValue* value, gpointer v_object);
gpointer value_get_component_inst (const GValue* value);
GType component_inst_get_type (void) G_GNUC_CONST;
GType tflipflop_component_state_get_type (void) G_GNUC_CONST;
gpointer connection_ref (gpointer instance);
void connection_unref (gpointer instance);
GParamSpec* param_spec_connection (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_connection (GValue* value, gpointer v_object);
void value_take_connection (GValue* value, gpointer v_object);
gpointer value_get_connection (const GValue* value);
GType connection_get_type (void) G_GNUC_CONST;
#define TFLIPFLOP_COMPONENT_STATE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_TFLIPFLOP_COMPONENT_STATE, TFlipflopComponentStatePrivate))
enum  {
	TFLIPFLOP_COMPONENT_STATE_DUMMY_PROPERTY
};
TFlipflopComponentState* tflipflop_component_state_new (Connection* toggleWire, Connection* clockWire, Connection* outputWire, Connection* outputNotWire, ComponentInst** ancestry, int ancestry_length1, ComponentInst* componentInst);
TFlipflopComponentState* tflipflop_component_state_construct (GType object_type, Connection* toggleWire, Connection* clockWire, Connection* outputWire, Connection* outputNotWire, ComponentInst** ancestry, int ancestry_length1, ComponentInst* componentInst);
ComponentState* component_state_construct (GType object_type);
void connection_set_affects (Connection* self, ComponentState* componentState);
static ComponentInst** _vala_array_dup36 (ComponentInst** self, int length);
static void tflipflop_component_state_real_update (ComponentState* base);
gboolean connection_get_signalState (Connection* self);
void connection_set_signalState (Connection* self, gboolean value);
static void tflipflop_component_state_finalize (ComponentState* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static gpointer _connection_ref0 (gpointer self) {
	return self ? connection_ref (self) : NULL;
}


static gpointer _component_inst_ref0 (gpointer self) {
	return self ? component_inst_ref (self) : NULL;
}


static ComponentInst** _vala_array_dup36 (ComponentInst** self, int length) {
	ComponentInst** result;
	int i;
	result = g_new0 (ComponentInst*, length + 1);
	for (i = 0; i < length; i++) {
		ComponentInst* _tmp0_ = NULL;
		_tmp0_ = _component_inst_ref0 (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


TFlipflopComponentState* tflipflop_component_state_construct (GType object_type, Connection* toggleWire, Connection* clockWire, Connection* outputWire, Connection* outputNotWire, ComponentInst** ancestry, int ancestry_length1, ComponentInst* componentInst) {
	TFlipflopComponentState* self = NULL;
	Connection* _tmp0_ = NULL;
	Connection* _tmp1_ = NULL;
	Connection* _tmp2_ = NULL;
	Connection* _tmp3_ = NULL;
	Connection* _tmp4_ = NULL;
	Connection* _tmp5_ = NULL;
	Connection* _tmp6_ = NULL;
	Connection* _tmp7_ = NULL;
	Connection* _tmp8_ = NULL;
	ComponentInst** _tmp9_ = NULL;
	gint _tmp9__length1 = 0;
	ComponentInst** _tmp10_ = NULL;
	gint _tmp10__length1 = 0;
	ComponentInst* _tmp11_ = NULL;
	ComponentInst* _tmp12_ = NULL;
	g_return_val_if_fail (toggleWire != NULL, NULL);
	g_return_val_if_fail (clockWire != NULL, NULL);
	g_return_val_if_fail (outputWire != NULL, NULL);
	g_return_val_if_fail (outputNotWire != NULL, NULL);
	g_return_val_if_fail (componentInst != NULL, NULL);
	self = (TFlipflopComponentState*) component_state_construct (object_type);
	_tmp0_ = toggleWire;
	_tmp1_ = _connection_ref0 (_tmp0_);
	_connection_unref0 (self->priv->toggleWire);
	self->priv->toggleWire = _tmp1_;
	_tmp2_ = clockWire;
	connection_set_affects (_tmp2_, (ComponentState*) self);
	_tmp3_ = clockWire;
	_tmp4_ = _connection_ref0 (_tmp3_);
	_connection_unref0 (self->priv->clockWire);
	self->priv->clockWire = _tmp4_;
	_tmp5_ = outputWire;
	_tmp6_ = _connection_ref0 (_tmp5_);
	_connection_unref0 (self->priv->outputWire);
	self->priv->outputWire = _tmp6_;
	_tmp7_ = outputNotWire;
	_tmp8_ = _connection_ref0 (_tmp7_);
	_connection_unref0 (self->priv->outputNotWire);
	self->priv->outputNotWire = _tmp8_;
	self->priv->output = FALSE;
	self->priv->previousClockSignal = TRUE;
	_tmp9_ = ancestry;
	_tmp9__length1 = ancestry_length1;
	_tmp10_ = (_tmp9_ != NULL) ? _vala_array_dup36 (_tmp9_, _tmp9__length1) : ((gpointer) _tmp9_);
	_tmp10__length1 = _tmp9__length1;
	((ComponentState*) self)->ancestry = (_vala_array_free (((ComponentState*) self)->ancestry, ((ComponentState*) self)->ancestry_length1, (GDestroyNotify) component_inst_unref), NULL);
	((ComponentState*) self)->ancestry = _tmp10_;
	((ComponentState*) self)->ancestry_length1 = _tmp10__length1;
	_tmp11_ = componentInst;
	_tmp12_ = _component_inst_ref0 (_tmp11_);
	_component_inst_unref0 (((ComponentState*) self)->componentInst);
	((ComponentState*) self)->componentInst = _tmp12_;
	return self;
}


TFlipflopComponentState* tflipflop_component_state_new (Connection* toggleWire, Connection* clockWire, Connection* outputWire, Connection* outputNotWire, ComponentInst** ancestry, int ancestry_length1, ComponentInst* componentInst) {
	return tflipflop_component_state_construct (TYPE_TFLIPFLOP_COMPONENT_STATE, toggleWire, clockWire, outputWire, outputNotWire, ancestry, ancestry_length1, componentInst);
}


static void tflipflop_component_state_real_update (ComponentState* base) {
	TFlipflopComponentState * self;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	Connection* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	gboolean _tmp4_ = FALSE;
	Connection* _tmp11_ = NULL;
	gboolean _tmp12_ = FALSE;
	gboolean _tmp13_ = FALSE;
	Connection* _tmp14_ = NULL;
	gboolean _tmp15_ = FALSE;
	Connection* _tmp16_ = NULL;
	gboolean _tmp17_ = FALSE;
	self = (TFlipflopComponentState*) base;
	_tmp2_ = self->priv->clockWire;
	_tmp3_ = connection_get_signalState (_tmp2_);
	_tmp4_ = _tmp3_;
	if (_tmp4_) {
		gboolean _tmp5_ = FALSE;
		_tmp5_ = self->priv->previousClockSignal;
		_tmp1_ = !_tmp5_;
	} else {
		_tmp1_ = FALSE;
	}
	if (_tmp1_) {
		Connection* _tmp6_ = NULL;
		gboolean _tmp7_ = FALSE;
		gboolean _tmp8_ = FALSE;
		_tmp6_ = self->priv->toggleWire;
		_tmp7_ = connection_get_signalState (_tmp6_);
		_tmp8_ = _tmp7_;
		_tmp0_ = _tmp8_;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		gboolean _tmp9_ = FALSE;
		gboolean _tmp10_ = FALSE;
		_tmp10_ = self->priv->output;
		if (_tmp10_) {
			_tmp9_ = FALSE;
		} else {
			_tmp9_ = TRUE;
		}
		self->priv->output = _tmp9_;
	}
	_tmp11_ = self->priv->clockWire;
	_tmp12_ = connection_get_signalState (_tmp11_);
	_tmp13_ = _tmp12_;
	self->priv->previousClockSignal = _tmp13_;
	_tmp14_ = self->priv->outputWire;
	_tmp15_ = self->priv->output;
	connection_set_signalState (_tmp14_, _tmp15_);
	_tmp16_ = self->priv->outputNotWire;
	_tmp17_ = self->priv->output;
	connection_set_signalState (_tmp16_, !_tmp17_);
}


static void tflipflop_component_state_class_init (TFlipflopComponentStateClass * klass) {
	tflipflop_component_state_parent_class = g_type_class_peek_parent (klass);
	COMPONENT_STATE_CLASS (klass)->finalize = tflipflop_component_state_finalize;
	g_type_class_add_private (klass, sizeof (TFlipflopComponentStatePrivate));
	COMPONENT_STATE_CLASS (klass)->update = tflipflop_component_state_real_update;
}


static void tflipflop_component_state_instance_init (TFlipflopComponentState * self) {
	self->priv = TFLIPFLOP_COMPONENT_STATE_GET_PRIVATE (self);
}


static void tflipflop_component_state_finalize (ComponentState* obj) {
	TFlipflopComponentState * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_TFLIPFLOP_COMPONENT_STATE, TFlipflopComponentState);
	_connection_unref0 (self->priv->toggleWire);
	_connection_unref0 (self->priv->clockWire);
	_connection_unref0 (self->priv->outputWire);
	_connection_unref0 (self->priv->outputNotWire);
	COMPONENT_STATE_CLASS (tflipflop_component_state_parent_class)->finalize (obj);
}


GType tflipflop_component_state_get_type (void) {
	static volatile gsize tflipflop_component_state_type_id__volatile = 0;
	if (g_once_init_enter (&tflipflop_component_state_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TFlipflopComponentStateClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) tflipflop_component_state_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TFlipflopComponentState), 0, (GInstanceInitFunc) tflipflop_component_state_instance_init, NULL };
		GType tflipflop_component_state_type_id;
		tflipflop_component_state_type_id = g_type_register_static (TYPE_COMPONENT_STATE, "TFlipflopComponentState", &g_define_type_info, 0);
		g_once_init_leave (&tflipflop_component_state_type_id__volatile, tflipflop_component_state_type_id);
	}
	return tflipflop_component_state_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



