/* propertyitem-selection.c generated by valac 0.16.0, the Vala compiler
 * generated from propertyitem-selection.vala, do not modify */

/* 
 * SmartSim - Digital Logic Circuit Designer and Simulator
 *   
 *   Expansion Version
 *   
 *   Filename: propertyitem/selection.vala
 *   
 *   Copyright Ashley Newson 2012
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_PROPERTY_ITEM (property_item_get_type ())
#define PROPERTY_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PROPERTY_ITEM, PropertyItem))
#define PROPERTY_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PROPERTY_ITEM, PropertyItemClass))
#define IS_PROPERTY_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PROPERTY_ITEM))
#define IS_PROPERTY_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PROPERTY_ITEM))
#define PROPERTY_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PROPERTY_ITEM, PropertyItemClass))

typedef struct _PropertyItem PropertyItem;
typedef struct _PropertyItemClass PropertyItemClass;
typedef struct _PropertyItemPrivate PropertyItemPrivate;

#define TYPE_PROPERTY_ITEM_SELECTION (property_item_selection_get_type ())
#define PROPERTY_ITEM_SELECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PROPERTY_ITEM_SELECTION, PropertyItemSelection))
#define PROPERTY_ITEM_SELECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PROPERTY_ITEM_SELECTION, PropertyItemSelectionClass))
#define IS_PROPERTY_ITEM_SELECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PROPERTY_ITEM_SELECTION))
#define IS_PROPERTY_ITEM_SELECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PROPERTY_ITEM_SELECTION))
#define PROPERTY_ITEM_SELECTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PROPERTY_ITEM_SELECTION, PropertyItemSelectionClass))

typedef struct _PropertyItemSelection PropertyItemSelection;
typedef struct _PropertyItemSelectionClass PropertyItemSelectionClass;
typedef struct _PropertyItemSelectionPrivate PropertyItemSelectionPrivate;

#define TYPE_PROPERTY_SET (property_set_get_type ())
#define PROPERTY_SET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PROPERTY_SET, PropertySet))
#define PROPERTY_SET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PROPERTY_SET, PropertySetClass))
#define IS_PROPERTY_SET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PROPERTY_SET))
#define IS_PROPERTY_SET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PROPERTY_SET))
#define PROPERTY_SET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PROPERTY_SET, PropertySetClass))

typedef struct _PropertySet PropertySet;
typedef struct _PropertySetClass PropertySetClass;
#define _property_item_unref0(var) ((var == NULL) ? NULL : (var = (property_item_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))

typedef enum  {
	PROPERTY_ITEM_STRING_ERROR_OPTION_NOT_FOUND
} PropertyItemStringError;
#define PROPERTY_ITEM_STRING_ERROR property_item_string_error_quark ()
struct _PropertyItem {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PropertyItemPrivate * priv;
	gchar* name;
	gchar* description;
};

struct _PropertyItemClass {
	GTypeClass parent_class;
	void (*finalize) (PropertyItem *self);
	GtkWidget* (*create_widget) (PropertyItem* self);
	void (*read_widget) (PropertyItem* self, GtkWidget* propertyWidget);
};

struct _PropertyItemSelection {
	PropertyItem parent_instance;
	PropertyItemSelectionPrivate * priv;
	gchar** options;
	gint options_length1;
};

struct _PropertyItemSelectionClass {
	PropertyItemClass parent_class;
};

struct _PropertyItemSelectionPrivate {
	gint _selected;
};

typedef enum  {
	PROPERTY_ITEM_ERROR_ITEM_NOT_FOUND
} PropertyItemError;
#define PROPERTY_ITEM_ERROR property_item_error_quark ()

static gpointer property_item_selection_parent_class = NULL;

GQuark property_item_string_error_quark (void);
gpointer property_item_ref (gpointer instance);
void property_item_unref (gpointer instance);
GParamSpec* param_spec_property_item (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_property_item (GValue* value, gpointer v_object);
void value_take_property_item (GValue* value, gpointer v_object);
gpointer value_get_property_item (const GValue* value);
GType property_item_get_type (void) G_GNUC_CONST;
GType property_item_selection_get_type (void) G_GNUC_CONST;
#define PROPERTY_ITEM_SELECTION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_PROPERTY_ITEM_SELECTION, PropertyItemSelectionPrivate))
enum  {
	PROPERTY_ITEM_SELECTION_DUMMY_PROPERTY
};
GType property_set_get_type (void) G_GNUC_CONST;
GQuark property_item_error_quark (void);
gchar* property_item_selection_get_data_throw (PropertySet* propertySet, const gchar* name, GError** error);
PropertyItem* property_set_get_item (PropertySet* self, const gchar* name);
gchar* property_item_selection_get_option (PropertyItemSelection* self);
void property_item_selection_set_data_throw (PropertySet* propertySet, const gchar* name, const gchar* option, GError** error);
gint property_item_selection_set_option (PropertyItemSelection* self, const gchar* option);
gchar* property_item_selection_get_data (PropertySet* propertySet, const gchar* name);
void property_item_selection_set_data (PropertySet* propertySet, const gchar* name, const gchar* option);
PropertyItemSelection* property_item_selection_new (const gchar* name, const gchar* description);
PropertyItemSelection* property_item_selection_construct (GType object_type, const gchar* name, const gchar* description);
PropertyItem* property_item_construct (GType object_type, const gchar* name, const gchar* description);
void property_item_selection_add_option (PropertyItemSelection* self, const gchar* option);
static gchar** _vala_array_dup93 (gchar** self, int length);
static void _vala_array_add105 (gchar*** array, int* length, int* size, gchar* value);
static gchar** _vala_array_dup94 (gchar** self, int length);
static gint property_item_selection_get_selected (PropertyItemSelection* self);
static void property_item_selection_set_selected (PropertyItemSelection* self, gint value);
static GtkWidget* property_item_selection_real_create_widget (PropertyItem* base);
static void _vala_array_add106 (GtkRadioButton*** array, int* length, int* size, GtkRadioButton* value);
static void property_item_selection_real_read_widget (PropertyItem* base, GtkWidget* propertyWidget);
static void property_item_selection_finalize (PropertyItem* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


GQuark property_item_string_error_quark (void) {
	return g_quark_from_static_string ("property_item_string_error-quark");
}


gchar* property_item_selection_get_data_throw (PropertySet* propertySet, const gchar* name, GError** error) {
	gchar* result = NULL;
	PropertySet* _tmp0_;
	const gchar* _tmp1_;
	PropertyItem* _tmp2_ = NULL;
	PropertyItem* propertyItem;
	PropertyItem* _tmp3_;
	PropertySet* _tmp7_;
	const gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	const gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	gchar* _tmp17_;
	GError* _tmp18_;
	GError* _tmp19_;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (propertySet != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	_tmp0_ = propertySet;
	_tmp1_ = name;
	_tmp2_ = property_set_get_item (_tmp0_, _tmp1_);
	propertyItem = _tmp2_;
	_tmp3_ = propertyItem;
	if (_tmp3_ != NULL) {
		PropertyItem* _tmp4_;
		_tmp4_ = propertyItem;
		if (IS_PROPERTY_ITEM_SELECTION (_tmp4_)) {
			PropertyItem* _tmp5_;
			gchar* _tmp6_ = NULL;
			_tmp5_ = propertyItem;
			_tmp6_ = property_item_selection_get_option (IS_PROPERTY_ITEM_SELECTION (_tmp5_) ? ((PropertyItemSelection*) _tmp5_) : NULL);
			result = _tmp6_;
			_property_item_unref0 (propertyItem);
			return result;
		}
	}
	_tmp7_ = propertySet;
	_tmp8_ = ((PropertyItem*) _tmp7_)->name;
	_tmp9_ = g_strconcat ("\"", _tmp8_, NULL);
	_tmp10_ = _tmp9_;
	_tmp11_ = g_strconcat (_tmp10_, "\" does not contain a selection named \"", NULL);
	_tmp12_ = _tmp11_;
	_tmp13_ = name;
	_tmp14_ = g_strconcat (_tmp12_, _tmp13_, NULL);
	_tmp15_ = _tmp14_;
	_tmp16_ = g_strconcat (_tmp15_, "\"", NULL);
	_tmp17_ = _tmp16_;
	_tmp18_ = g_error_new_literal (PROPERTY_ITEM_ERROR, PROPERTY_ITEM_ERROR_ITEM_NOT_FOUND, _tmp17_);
	_tmp19_ = _tmp18_;
	_g_free0 (_tmp17_);
	_g_free0 (_tmp15_);
	_g_free0 (_tmp12_);
	_g_free0 (_tmp10_);
	_inner_error_ = _tmp19_;
	if (_inner_error_->domain == PROPERTY_ITEM_ERROR) {
		g_propagate_error (error, _inner_error_);
		_property_item_unref0 (propertyItem);
		return NULL;
	} else {
		_property_item_unref0 (propertyItem);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_property_item_unref0 (propertyItem);
}


void property_item_selection_set_data_throw (PropertySet* propertySet, const gchar* name, const gchar* option, GError** error) {
	PropertySet* _tmp0_;
	const gchar* _tmp1_;
	PropertyItem* _tmp2_ = NULL;
	PropertyItem* propertyItem;
	PropertyItem* _tmp3_;
	PropertySet* _tmp26_;
	const gchar* _tmp27_;
	gchar* _tmp28_;
	gchar* _tmp29_;
	gchar* _tmp30_;
	gchar* _tmp31_;
	const gchar* _tmp32_;
	gchar* _tmp33_;
	gchar* _tmp34_;
	gchar* _tmp35_;
	gchar* _tmp36_;
	GError* _tmp37_;
	GError* _tmp38_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (propertySet != NULL);
	g_return_if_fail (name != NULL);
	g_return_if_fail (option != NULL);
	_tmp0_ = propertySet;
	_tmp1_ = name;
	_tmp2_ = property_set_get_item (_tmp0_, _tmp1_);
	propertyItem = _tmp2_;
	_tmp3_ = propertyItem;
	if (_tmp3_ != NULL) {
		PropertyItem* _tmp4_;
		_tmp4_ = propertyItem;
		if (IS_PROPERTY_ITEM_SELECTION (_tmp4_)) {
			PropertyItem* _tmp5_;
			const gchar* _tmp6_;
			gint _tmp7_ = 0;
			_tmp5_ = propertyItem;
			_tmp6_ = option;
			_tmp7_ = property_item_selection_set_option (IS_PROPERTY_ITEM_SELECTION (_tmp5_) ? ((PropertyItemSelection*) _tmp5_) : NULL, _tmp6_);
			if (_tmp7_ == 1) {
				PropertySet* _tmp8_;
				const gchar* _tmp9_;
				gchar* _tmp10_;
				gchar* _tmp11_;
				gchar* _tmp12_;
				gchar* _tmp13_;
				const gchar* _tmp14_;
				gchar* _tmp15_;
				gchar* _tmp16_;
				gchar* _tmp17_;
				gchar* _tmp18_;
				const gchar* _tmp19_;
				gchar* _tmp20_;
				gchar* _tmp21_;
				gchar* _tmp22_;
				gchar* _tmp23_;
				GError* _tmp24_;
				GError* _tmp25_;
				_tmp8_ = propertySet;
				_tmp9_ = ((PropertyItem*) _tmp8_)->name;
				_tmp10_ = g_strconcat ("\"", _tmp9_, NULL);
				_tmp11_ = _tmp10_;
				_tmp12_ = g_strconcat (_tmp11_, "\"'s selection named \"", NULL);
				_tmp13_ = _tmp12_;
				_tmp14_ = name;
				_tmp15_ = g_strconcat (_tmp13_, _tmp14_, NULL);
				_tmp16_ = _tmp15_;
				_tmp17_ = g_strconcat (_tmp16_, "\" does not contain option \"", NULL);
				_tmp18_ = _tmp17_;
				_tmp19_ = option;
				_tmp20_ = g_strconcat (_tmp18_, _tmp19_, NULL);
				_tmp21_ = _tmp20_;
				_tmp22_ = g_strconcat (_tmp21_, "\"", NULL);
				_tmp23_ = _tmp22_;
				_tmp24_ = g_error_new_literal (PROPERTY_ITEM_STRING_ERROR, PROPERTY_ITEM_STRING_ERROR_OPTION_NOT_FOUND, _tmp23_);
				_tmp25_ = _tmp24_;
				_g_free0 (_tmp23_);
				_g_free0 (_tmp21_);
				_g_free0 (_tmp18_);
				_g_free0 (_tmp16_);
				_g_free0 (_tmp13_);
				_g_free0 (_tmp11_);
				_inner_error_ = _tmp25_;
				if ((_inner_error_->domain == PROPERTY_ITEM_ERROR) || (_inner_error_->domain == PROPERTY_ITEM_STRING_ERROR)) {
					g_propagate_error (error, _inner_error_);
					_property_item_unref0 (propertyItem);
					return;
				} else {
					_property_item_unref0 (propertyItem);
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return;
				}
			}
			_property_item_unref0 (propertyItem);
			return;
		}
	}
	_tmp26_ = propertySet;
	_tmp27_ = ((PropertyItem*) _tmp26_)->name;
	_tmp28_ = g_strconcat ("\"", _tmp27_, NULL);
	_tmp29_ = _tmp28_;
	_tmp30_ = g_strconcat (_tmp29_, "\" does not contain a selection named \"", NULL);
	_tmp31_ = _tmp30_;
	_tmp32_ = name;
	_tmp33_ = g_strconcat (_tmp31_, _tmp32_, NULL);
	_tmp34_ = _tmp33_;
	_tmp35_ = g_strconcat (_tmp34_, "\"", NULL);
	_tmp36_ = _tmp35_;
	_tmp37_ = g_error_new_literal (PROPERTY_ITEM_ERROR, PROPERTY_ITEM_ERROR_ITEM_NOT_FOUND, _tmp36_);
	_tmp38_ = _tmp37_;
	_g_free0 (_tmp36_);
	_g_free0 (_tmp34_);
	_g_free0 (_tmp31_);
	_g_free0 (_tmp29_);
	_inner_error_ = _tmp38_;
	if ((_inner_error_->domain == PROPERTY_ITEM_ERROR) || (_inner_error_->domain == PROPERTY_ITEM_STRING_ERROR)) {
		g_propagate_error (error, _inner_error_);
		_property_item_unref0 (propertyItem);
		return;
	} else {
		_property_item_unref0 (propertyItem);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_property_item_unref0 (propertyItem);
}


gchar* property_item_selection_get_data (PropertySet* propertySet, const gchar* name) {
	gchar* result = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (propertySet != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	{
		PropertySet* _tmp0_;
		const gchar* _tmp1_;
		gchar* _tmp2_ = NULL;
		gchar* _tmp3_;
		_tmp0_ = propertySet;
		_tmp1_ = name;
		_tmp2_ = property_item_selection_get_data_throw (_tmp0_, _tmp1_, &_inner_error_);
		_tmp3_ = _tmp2_;
		if (_inner_error_ != NULL) {
			goto __catch60_g_error;
		}
		result = _tmp3_;
		return result;
	}
	goto __finally60;
	__catch60_g_error:
	{
		gchar* _tmp4_;
		g_clear_error (&_inner_error_);
		_inner_error_ = NULL;
		_tmp4_ = g_strdup ("");
		result = _tmp4_;
		return result;
	}
	__finally60:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return NULL;
}


void property_item_selection_set_data (PropertySet* propertySet, const gchar* name, const gchar* option) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (propertySet != NULL);
	g_return_if_fail (name != NULL);
	g_return_if_fail (option != NULL);
	{
		PropertySet* _tmp0_;
		const gchar* _tmp1_;
		const gchar* _tmp2_;
		_tmp0_ = propertySet;
		_tmp1_ = name;
		_tmp2_ = option;
		property_item_selection_set_data_throw (_tmp0_, _tmp1_, _tmp2_, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch61_g_error;
		}
	}
	goto __finally61;
	__catch61_g_error:
	{
		g_clear_error (&_inner_error_);
		_inner_error_ = NULL;
	}
	__finally61:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


PropertyItemSelection* property_item_selection_construct (GType object_type, const gchar* name, const gchar* description) {
	PropertyItemSelection* self = NULL;
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	gchar** _tmp2_ = NULL;
	g_return_val_if_fail (name != NULL, NULL);
	g_return_val_if_fail (description != NULL, NULL);
	_tmp0_ = name;
	_tmp1_ = description;
	self = (PropertyItemSelection*) property_item_construct (object_type, _tmp0_, _tmp1_);
	_tmp2_ = g_new0 (gchar*, 0 + 1);
	self->options = (_vala_array_free (self->options, self->options_length1, (GDestroyNotify) g_free), NULL);
	self->options = _tmp2_;
	self->options_length1 = 0;
	self->priv->_selected = 0;
	return self;
}


PropertyItemSelection* property_item_selection_new (const gchar* name, const gchar* description) {
	return property_item_selection_construct (TYPE_PROPERTY_ITEM_SELECTION, name, description);
}


static gchar** _vala_array_dup93 (gchar** self, int length) {
	gchar** result;
	int i;
	result = g_new0 (gchar*, length + 1);
	for (i = 0; i < length; i++) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


static void _vala_array_add105 (gchar*** array, int* length, int* size, gchar* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static gchar** _vala_array_dup94 (gchar** self, int length) {
	gchar** result;
	int i;
	result = g_new0 (gchar*, length + 1);
	for (i = 0; i < length; i++) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


void property_item_selection_add_option (PropertyItemSelection* self, const gchar* option) {
	gchar** _tmp0_;
	gint _tmp0__length1;
	gchar** _tmp1_;
	gint _tmp1__length1;
	gchar** newOptions;
	gint newOptions_length1;
	gint _newOptions_size_;
	gchar** _tmp2_;
	gint _tmp2__length1;
	const gchar* _tmp3_;
	gchar* _tmp4_;
	gchar** _tmp5_;
	gint _tmp5__length1;
	gchar** _tmp6_;
	gint _tmp6__length1;
	g_return_if_fail (self != NULL);
	g_return_if_fail (option != NULL);
	_tmp0_ = self->options;
	_tmp0__length1 = self->options_length1;
	_tmp1_ = (_tmp0_ != NULL) ? _vala_array_dup93 (_tmp0_, _tmp0__length1) : ((gpointer) _tmp0_);
	_tmp1__length1 = _tmp0__length1;
	newOptions = _tmp1_;
	newOptions_length1 = _tmp1__length1;
	_newOptions_size_ = newOptions_length1;
	_tmp2_ = newOptions;
	_tmp2__length1 = newOptions_length1;
	_tmp3_ = option;
	_tmp4_ = g_strdup (_tmp3_);
	_vala_array_add105 (&newOptions, &newOptions_length1, &_newOptions_size_, _tmp4_);
	_tmp5_ = newOptions;
	_tmp5__length1 = newOptions_length1;
	_tmp6_ = (_tmp5_ != NULL) ? _vala_array_dup94 (_tmp5_, _tmp5__length1) : ((gpointer) _tmp5_);
	_tmp6__length1 = _tmp5__length1;
	self->options = (_vala_array_free (self->options, self->options_length1, (GDestroyNotify) g_free), NULL);
	self->options = _tmp6_;
	self->options_length1 = _tmp6__length1;
	newOptions = (_vala_array_free (newOptions, newOptions_length1, (GDestroyNotify) g_free), NULL);
}


gchar* property_item_selection_get_option (PropertyItemSelection* self) {
	gchar* result = NULL;
	gchar** _tmp0_;
	gint _tmp0__length1;
	gchar** _tmp2_;
	gint _tmp2__length1;
	gint _tmp3_;
	gint _tmp4_;
	const gchar* _tmp5_;
	gchar* _tmp6_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->options;
	_tmp0__length1 = self->options_length1;
	if (_tmp0__length1 == 0) {
		gchar* _tmp1_;
		_tmp1_ = g_strdup ("");
		result = _tmp1_;
		return result;
	}
	_tmp2_ = self->options;
	_tmp2__length1 = self->options_length1;
	_tmp3_ = property_item_selection_get_selected (self);
	_tmp4_ = _tmp3_;
	_tmp5_ = _tmp2_[_tmp4_];
	_tmp6_ = g_strdup (_tmp5_);
	result = _tmp6_;
	return result;
}


gint property_item_selection_set_option (PropertyItemSelection* self, const gchar* option) {
	gint result = 0;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (option != NULL, 0);
	{
		gint i;
		i = 0;
		{
			gboolean _tmp0_;
			_tmp0_ = TRUE;
			while (TRUE) {
				gboolean _tmp1_;
				gint _tmp3_;
				gchar** _tmp4_;
				gint _tmp4__length1;
				const gchar* _tmp5_;
				gchar** _tmp6_;
				gint _tmp6__length1;
				gint _tmp7_;
				const gchar* _tmp8_;
				_tmp1_ = _tmp0_;
				if (!_tmp1_) {
					gint _tmp2_;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp3_ = i;
				_tmp4_ = self->options;
				_tmp4__length1 = self->options_length1;
				if (!(_tmp3_ < _tmp4__length1)) {
					break;
				}
				_tmp5_ = option;
				_tmp6_ = self->options;
				_tmp6__length1 = self->options_length1;
				_tmp7_ = i;
				_tmp8_ = _tmp6_[_tmp7_];
				if (g_strcmp0 (_tmp5_, _tmp8_) == 0) {
					gint _tmp9_;
					_tmp9_ = i;
					property_item_selection_set_selected (self, _tmp9_);
					result = 0;
					return result;
				}
			}
		}
	}
	result = 1;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void _vala_array_add106 (GtkRadioButton*** array, int* length, int* size, GtkRadioButton* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (GtkRadioButton*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static GtkWidget* property_item_selection_real_create_widget (PropertyItem* base) {
	PropertyItemSelection * self;
	GtkWidget* result = NULL;
	gchar** _tmp0_;
	gint _tmp0__length1;
	gint numberOfOptions;
	GtkVBox* _tmp1_;
	GtkVBox* _tmp2_;
	GtkVBox* vBox;
	GtkRadioButton** _tmp3_ = NULL;
	GtkRadioButton** radioButtons;
	gint radioButtons_length1;
	gint _radioButtons_size_;
	gint _tmp27_;
	self = (PropertyItemSelection*) base;
	_tmp0_ = self->options;
	_tmp0__length1 = self->options_length1;
	numberOfOptions = _tmp0__length1;
	_tmp1_ = (GtkVBox*) gtk_vbox_new (FALSE, 1);
	_tmp2_ = g_object_ref_sink (_tmp1_);
	vBox = _tmp2_;
	_tmp3_ = g_new0 (GtkRadioButton*, 0 + 1);
	radioButtons = _tmp3_;
	radioButtons_length1 = 0;
	_radioButtons_size_ = radioButtons_length1;
	{
		gint i;
		i = 0;
		{
			gboolean _tmp4_;
			_tmp4_ = TRUE;
			while (TRUE) {
				gboolean _tmp5_;
				gint _tmp7_;
				gint _tmp8_;
				GtkRadioButton* radioButton = NULL;
				gint _tmp9_;
				GtkRadioButton** _tmp22_;
				gint _tmp22__length1;
				GtkRadioButton* _tmp23_;
				GtkRadioButton* _tmp24_;
				GtkVBox* _tmp25_;
				GtkRadioButton* _tmp26_;
				_tmp5_ = _tmp4_;
				if (!_tmp5_) {
					gint _tmp6_;
					_tmp6_ = i;
					i = _tmp6_ + 1;
				}
				_tmp4_ = FALSE;
				_tmp7_ = i;
				_tmp8_ = numberOfOptions;
				if (!(_tmp7_ < _tmp8_)) {
					break;
				}
				_tmp9_ = i;
				if (_tmp9_ == 0) {
					gchar** _tmp10_;
					gint _tmp10__length1;
					gint _tmp11_;
					const gchar* _tmp12_;
					GtkRadioButton* _tmp13_;
					GtkRadioButton* _tmp14_;
					_tmp10_ = self->options;
					_tmp10__length1 = self->options_length1;
					_tmp11_ = i;
					_tmp12_ = _tmp10_[_tmp11_];
					_tmp13_ = (GtkRadioButton*) gtk_radio_button_new_with_label (NULL, _tmp12_);
					_tmp14_ = g_object_ref_sink (_tmp13_);
					_g_object_unref0 (radioButton);
					radioButton = _tmp14_;
				} else {
					GtkRadioButton** _tmp15_;
					gint _tmp15__length1;
					GtkRadioButton* _tmp16_;
					gchar** _tmp17_;
					gint _tmp17__length1;
					gint _tmp18_;
					const gchar* _tmp19_;
					GtkRadioButton* _tmp20_;
					GtkRadioButton* _tmp21_;
					_tmp15_ = radioButtons;
					_tmp15__length1 = radioButtons_length1;
					_tmp16_ = _tmp15_[0];
					_tmp17_ = self->options;
					_tmp17__length1 = self->options_length1;
					_tmp18_ = i;
					_tmp19_ = _tmp17_[_tmp18_];
					_tmp20_ = (GtkRadioButton*) gtk_radio_button_new_with_label_from_widget (_tmp16_, _tmp19_);
					_tmp21_ = g_object_ref_sink (_tmp20_);
					_g_object_unref0 (radioButton);
					radioButton = _tmp21_;
				}
				_tmp22_ = radioButtons;
				_tmp22__length1 = radioButtons_length1;
				_tmp23_ = radioButton;
				_tmp24_ = _g_object_ref0 (_tmp23_);
				_vala_array_add106 (&radioButtons, &radioButtons_length1, &_radioButtons_size_, _tmp24_);
				_tmp25_ = vBox;
				_tmp26_ = radioButton;
				gtk_box_pack_start ((GtkBox*) _tmp25_, (GtkWidget*) _tmp26_, FALSE, TRUE, (guint) 1);
				_g_object_unref0 (radioButton);
			}
		}
	}
	_tmp27_ = numberOfOptions;
	if (_tmp27_ > 0) {
		GtkRadioButton** _tmp28_;
		gint _tmp28__length1;
		gint _tmp29_;
		gint _tmp30_;
		GtkRadioButton* _tmp31_;
		_tmp28_ = radioButtons;
		_tmp28__length1 = radioButtons_length1;
		_tmp29_ = property_item_selection_get_selected (self);
		_tmp30_ = _tmp29_;
		_tmp31_ = _tmp28_[_tmp30_];
		gtk_toggle_button_set_active ((GtkToggleButton*) _tmp31_, TRUE);
	}
	result = (GtkWidget*) vBox;
	radioButtons = (_vala_array_free (radioButtons, radioButtons_length1, (GDestroyNotify) g_object_unref), NULL);
	return result;
}


static void property_item_selection_real_read_widget (PropertyItem* base, GtkWidget* propertyWidget) {
	PropertyItemSelection * self;
	GtkWidget* _tmp0_;
	self = (PropertyItemSelection*) base;
	g_return_if_fail (propertyWidget != NULL);
	_tmp0_ = propertyWidget;
	if (_tmp0_ != NULL) {
		GtkWidget* _tmp1_;
		_tmp1_ = propertyWidget;
		if (GTK_IS_VBOX (_tmp1_)) {
			GtkWidget* _tmp2_;
			GtkVBox* _tmp3_;
			GtkVBox* vBox;
			GtkVBox* _tmp4_;
			GList* _tmp5_ = NULL;
			GList* radioButtons;
			GList* _tmp6_;
			guint _tmp7_ = 0U;
			gchar** _tmp8_;
			gint _tmp8__length1;
			_tmp2_ = propertyWidget;
			_tmp3_ = _g_object_ref0 (GTK_IS_VBOX (_tmp2_) ? ((GtkVBox*) _tmp2_) : NULL);
			vBox = _tmp3_;
			_tmp4_ = vBox;
			_tmp5_ = gtk_container_get_children ((GtkContainer*) _tmp4_);
			radioButtons = _tmp5_;
			_tmp6_ = radioButtons;
			_tmp7_ = g_list_length (_tmp6_);
			_tmp8_ = self->options;
			_tmp8__length1 = self->options_length1;
			if (_tmp7_ == ((guint) _tmp8__length1)) {
				{
					gint i;
					i = 0;
					{
						gboolean _tmp9_;
						_tmp9_ = TRUE;
						while (TRUE) {
							gboolean _tmp10_;
							gint _tmp12_;
							gchar** _tmp13_;
							gint _tmp13__length1;
							GList* _tmp14_;
							gint _tmp15_;
							gconstpointer _tmp16_ = NULL;
							GtkWidget* _tmp17_;
							GtkWidget* widget;
							GtkWidget* _tmp18_;
							_tmp10_ = _tmp9_;
							if (!_tmp10_) {
								gint _tmp11_;
								_tmp11_ = i;
								i = _tmp11_ + 1;
							}
							_tmp9_ = FALSE;
							_tmp12_ = i;
							_tmp13_ = self->options;
							_tmp13__length1 = self->options_length1;
							if (!(_tmp12_ < _tmp13__length1)) {
								break;
							}
							_tmp14_ = radioButtons;
							_tmp15_ = i;
							_tmp16_ = g_list_nth_data (_tmp14_, (guint) _tmp15_);
							_tmp17_ = _g_object_ref0 ((GtkWidget*) _tmp16_);
							widget = _tmp17_;
							_tmp18_ = widget;
							if (GTK_IS_RADIO_BUTTON (_tmp18_)) {
								GtkWidget* _tmp19_;
								gboolean _tmp20_;
								gboolean _tmp21_;
								_tmp19_ = widget;
								_tmp20_ = gtk_toggle_button_get_active ((GtkToggleButton*) (GTK_IS_RADIO_BUTTON (_tmp19_) ? ((GtkRadioButton*) _tmp19_) : NULL));
								_tmp21_ = _tmp20_;
								if (_tmp21_ == TRUE) {
									gint _tmp22_;
									_tmp22_ = i;
									property_item_selection_set_selected (self, _tmp22_);
									_g_object_unref0 (widget);
									_g_list_free0 (radioButtons);
									_g_object_unref0 (vBox);
									return;
								}
							}
							_g_object_unref0 (widget);
						}
					}
				}
			}
			_g_list_free0 (radioButtons);
			_g_object_unref0 (vBox);
		}
	}
}


static gint property_item_selection_get_selected (PropertyItemSelection* self) {
	gint result;
	gint _tmp0_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_selected;
	result = _tmp0_;
	return result;
}


static void property_item_selection_set_selected (PropertyItemSelection* self, gint value) {
	gboolean _tmp0_ = FALSE;
	gint _tmp1_;
	gboolean _tmp4_;
	g_return_if_fail (self != NULL);
	_tmp1_ = value;
	if (_tmp1_ >= 0) {
		gint _tmp2_;
		gchar** _tmp3_;
		gint _tmp3__length1;
		_tmp2_ = value;
		_tmp3_ = self->options;
		_tmp3__length1 = self->options_length1;
		_tmp0_ = _tmp2_ < _tmp3__length1;
	} else {
		_tmp0_ = FALSE;
	}
	_tmp4_ = _tmp0_;
	if (_tmp4_) {
		gint _tmp5_;
		_tmp5_ = value;
		self->priv->_selected = _tmp5_;
	}
}


static void property_item_selection_class_init (PropertyItemSelectionClass * klass) {
	property_item_selection_parent_class = g_type_class_peek_parent (klass);
	PROPERTY_ITEM_CLASS (klass)->finalize = property_item_selection_finalize;
	g_type_class_add_private (klass, sizeof (PropertyItemSelectionPrivate));
	PROPERTY_ITEM_CLASS (klass)->create_widget = property_item_selection_real_create_widget;
	PROPERTY_ITEM_CLASS (klass)->read_widget = property_item_selection_real_read_widget;
}


static void property_item_selection_instance_init (PropertyItemSelection * self) {
	self->priv = PROPERTY_ITEM_SELECTION_GET_PRIVATE (self);
}


static void property_item_selection_finalize (PropertyItem* obj) {
	PropertyItemSelection * self;
	self = PROPERTY_ITEM_SELECTION (obj);
	self->options = (_vala_array_free (self->options, self->options_length1, (GDestroyNotify) g_free), NULL);
	PROPERTY_ITEM_CLASS (property_item_selection_parent_class)->finalize (obj);
}


GType property_item_selection_get_type (void) {
	static volatile gsize property_item_selection_type_id__volatile = 0;
	if (g_once_init_enter (&property_item_selection_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PropertyItemSelectionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) property_item_selection_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PropertyItemSelection), 0, (GInstanceInitFunc) property_item_selection_instance_init, NULL };
		GType property_item_selection_type_id;
		property_item_selection_type_id = g_type_register_static (TYPE_PROPERTY_ITEM, "PropertyItemSelection", &g_define_type_info, 0);
		g_once_init_leave (&property_item_selection_type_id__volatile, property_item_selection_type_id);
	}
	return property_item_selection_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



